name: 'Trigger Jenkins Multiple Jobs'
description: 'Triggering Jenkins Job through the API'
author: 'Bo-Yi Wu'
inputs:
  url: http://jenkins-qa.internal-nprod.incred.com
    description: 'jenkins base url'
  user: ${{ secrets.JENKINS_USERNAME }}
    description: 'jenkins username'
  token: ${{ secrets.JENKINS_PAT }}
    description: 'jenkins api token'
  job: ${{ secrets.JENKINS_JOB }}
    description: 'jenkins job'
runs: 
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'check-circle'
  color: 'green'
