name: 'Trigger Jenkins Multiple Jobs'
description: 'Triggering Jenkins Job through the API'
author: 'Bo-Yi Wu'
inputs:
  url: 'http://jenkins-qa.internal-nprod.incred.com'
  user: ${{ secrets.JENKINS_USERNAME }}
  token: ${{ secrets.JENKINS_PAT }}
  job: ${{ secrets.JENKINS_JOB }}
runs: 
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'check-circle'
  color: 'green'
