name: 'Trigger Jenkins Multiple Jobs'
description: 'Triggering Jenkins Job through the API'
author: 'Bo-Yi Wu'
inputs:
  url: http://jenkins-qa.internal-nprod.incred.com
    description: 'jenkins base url'
  user: raghu
    description: 'jenkins username'
  token: 11acccba7fdb2d235539c0739e0aade4a8
    description: 'jenkins api token'
  job: RepaymentMicroservices
    description: 'jenkins job'
runs: 
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'check-circle'
  color: 'green'
